<#
.SYNOPSIS
Restore all unmanaged files backed-up by `Backup-UnamangedFiles` before.

.DESCRIPTION
Restore all unmanaged files backed-up by `Backup-UnamangedFiles` before.
After the backup is restored, it will be deleted.

.PARAMETER WebPath
The path where the files should be restored to.

.PARAMETER TempPath
The temp path generated by `Backup-UnamangedFiles`

.EXAMPLE
Restore-UnmanagedFiles -WebPath d:\webs\my -TempPath $backupPath

#>
function Restore-UnmanagedFiles
{
    [CmdletBinding()]
    Param(
      [Parameter(Mandatory=$true)]
      [string] $WebPath,
      [Parameter(Mandatory=$true)]
      [string] $TempPath

    )
    Process
    {
        cp $TempPath\* $WebPath -Recurse -Force

        rm $TempPath -Recurse
    }
}
